name: Deploy Python App

on:
  push:
    branches:
      - main 
      # Defining at worklflow level
env: 
  # This from the repository secrets
  DATABASE_CONNECTION_STRING: ${{ secrets.DATABASE_CONNECTION_STRING }}
jobs:
  test:
  # Defining at job level
  # Env is used for defining environment variables
    environment: Dev
    env:
      # This is from the environment secrets
      DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Logging
        run: echo "Database Name - ${{ env.DATABASE_NAME }}"

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Logging
         # Because is it available at workflow level
        # run: echo "Database Connection String - ${{ env.DATABASE_CONNECTION_STRING }}"
        run: echo "Database Connection String - ${{ env.NAME }}"
     
        