name: Deploy Python App

on:
  push:
    branches:
      - main 
      # Defining at worklflow level
env: 
  DATABASE_CONNECTION_STRING: postgresql://user:password@localhost:5432/dbname
  # DATABASE_CONNECTION_STRING: ${{ secrets.DATABASE }}

jobs:
  test:
  # Defining at job level
    env:
      DATABASE_NAME: customer_db
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Logging
        run: echo "Database Name - ${{ env.DATABASE_NAME }}"
          # echo Database Name: ${{ env.DATABASE_NAME }}

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Logging
         # Because is it available at workflow level
        run: echo "Database Connection String - ${{ env.DATABASE_CONNECTION_STRING }}"
     
        